server:
  port: 9527

spring:
  application:
    name: cloud-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能
      routes:
        - id: cloud-payment-service #路由的id建议用服务名
          uri: lb://cloud-payment-service # 匹配后提供服务的地址
          predicates:
            - Path=/payment/*/**
#            - Cookie=username,daiyuanjing

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
